baseURL = "https://yigit.run/"
languageCode = "en-us"
theme = "terminal"
googleAnalytics = "G-JXGYSDK9HK"
disqusShortname = "fr1nge-xyz"
title = "Yigit's Personal Blog"

[params]
  contentTypeName = "posts"

  themeColor = "blue"

  showMenuItems = 4

  showLanguageSelector = false

  fullWidthTheme = false

  centerTheme = true
  # favicon = "favicon.ico"

  showLastUpdated =  true
  enableGitInfo = true

[params.twitter]
  creator = "yigitclkl"
  site = "yigitcolakoglu.com"

[languages]
  [languages.en]
    languageName = "English"
    title = "Fr1nge's Personal Blog"
    subtitle = "Yigit Colakoglu aka. Fr1nge's Personal Blog"
    owner = "Yigit Colakoglu"
    keywords = "Tech, Linux, Programming, Security"
    copyright = "Yigit Colakoglu"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "yigit.run"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
      [[languages.en.menu.main]]
        identifier = "awards"
        name = "Awards & Certificates"
        url = "/awards"
